export const TASKS = [
  {
    code: "10.10",
    category: "Trabajos preliminares",
    task: "Presentación Municipal",
    inc_percent: "1400%",
    inc_m2: 100.52,
    total_without_computation: 100.0,
    unit: "%",
  },
  {
    code: "10.20",
    category: "Trabajos preliminares",
    task: "Empalizada y bandeja de protección",
    inc_percent: "200%",
    inc_m2: 14.36,
    total_without_computation: 100.0,
    unit: "%",
  },
  {
    code: "10.30",
    category: "Trabajos preliminares",
    task: "Demolición",
    inc_percent: "2000%",
    inc_m2: 143.6,
    total_without_computation: 624.0,
    unit: "m²",
  },
  {
    code: "10.40",
    category: "Trabajos preliminares",
    task: "Limpieza terreno",
    inc_percent: "200%",
    inc_m2: 14.36,
    total_without_computation: 100.0,
    unit: "%",
  },
  {
    code: "10.50",
    category: "Trabajos preliminares",
    task: "Obrador",
    inc_percent: "200%",
    inc_m2: 14.36,
    total_without_computation: 100.0,
    unit: "%",
  },
  {
    code: "20.10",
    category: "EXCAVACIÓN - ARMADO Y LLENADO DE BASES H° A°",
    task: "Replanteo de terreno y bases",
    inc_percent: "330%",
    inc_m2: 23.69,
    total_without_computation: 100.0,
    unit: "%",
  },
  {
    code: "20.20",
    category: "EXCAVACIÓN - ARMADO Y LLENADO DE BASES H° A°",
    task: "Excavaciones y movimiento de suelo",
    inc_percent: "1650%",
    inc_m2: 118.47,
    total_without_computation: 4300.0,
    unit: "m³",
  },
  {
    code: "20.30",
    category: "EXCAVACIÓN - ARMADO Y LLENADO DE BASES H° A°",
    task: "Armado y llenado de bases H° A°",
    inc_percent: "4620%",
    inc_m2: 331.72,
    total_without_computation: 350.0,
    unit: "m³",
  },
  {
    code: "30.10",
    category: "ESTRUCTURA H°A°",
    task: "Armado de encofrados y hierros.",
    inc_percent: "13200%",
    inc_m2: 947.76,
    total_without_computation: 850.0,
    unit: "m³",
  },
  {
    code: "30.20",
    category: "ESTRUCTURA H°A°",
    task: "Llenado H°A°",
    inc_percent: "13200%",
    inc_m2: 947.76,
    total_without_computation: 850.0,
    unit: "m³",
  },
  {
    code: "40.10",
    category: "ALBAÑILERIA",
    task: "Replanteo de mamposteria",
    inc_percent: "400%",
    inc_m2: 28.72,
    total_without_computation: 100.0,
    unit: "%",
  },
  {
    code: "40.100",
    category: "ALBAÑILERIA",
    task: "Impermeabilización de terraza y tanques",
    inc_percent: "400%",
    inc_m2: 28.72,
    total_without_computation: 100.0,
    unit: "%",
  },
  {
    code: "40.110",
    category: "ALBAÑILERIA",
    task: "Contrapiso y carpeta en balcones",
    inc_percent: "400%",
    inc_m2: 28.72,
    total_without_computation: 100.0,
    unit: "%",
  },
  {
    code: "40.120",
    category: "ALBAÑILERIA",
    task: "Mamposteria P.B. y subsuelo",
    inc_percent: "400%",
    inc_m2: 28.72,
    total_without_computation: 100.0,
    unit: "%",
  },
];
